service: collar-service
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage,'local'}
  memorySize: 1024
  timeout: 30
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

functions:
  graphql:
    handler: src/v1/graphql/handler.graphql
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get