service: collar-service
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage,'local'}
  memorySize: 1024
  timeout: 30
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - cloudformation: CreateStack
        - cloudformation: DescribeStacks
        - cloudformation: CreateChangeSet
        - cloudformation: ListStacks
        - cloudformation: UpdateStack
        - cloudformation: DescribeChangeSet
        - cloudformation: ExecuteChangeSet
        - iam: GetRole
        - lambda: UpdateFunctionCode
        - lambda: UpdateFunctionConfig
        - lambda: GetFunctionConfiguration
        - lambda: AddPermission
        - s3: GetObject
      Resource: "*"

functions:
  graphql:
    handler: src/v1/graphql/handler.graphql
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get